apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-mgiy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-mgiy
    app.kubernetes.io/part-of: test-app-jlgq
  name: test-component-mgiy
  namespace: build-e2e-xird-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-mgiy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-mgiy
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images:55f688fcb0ec4c44ada1802faec65841
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
